name = "minna-car"
main = "src/index.js"
compatibility_date = "2024-09-25"

[vars]
SITE_NAME = "みんなの車部"

[[d1_databases]]
binding = "DB"
database_name = "minna-car-db"
database_id = "placeholder"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "minna-car-images"
