name = "minna-car"
main = "src/index.js"
compatibility_date = "2024-09-25"

[vars]
SITE_NAME = "みんなの車部"

[[kv_namespaces]]
binding = "KV"
id = "f8127820c06d492c972972726af756e3"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "minna-car-images"
